# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANT_VERSION = "2.2.7"
VAGRANT_DEV_VERSION = "2.2.8"

Vagrant.configure("2") do |config|
  config.vm.define "windows-hyperv" do |windows|
    windows.vm.box = "StefanScherer/windows_10" # hyper-v

    #windows.vm.communicator = :winssh
    #windows.ssh.username = "vagrant"
    #windows.ssh.password = "vagrant"
    #windows.winssh.shell = "powershell"

    windows.vm.provision "Info", type: "shell", path: "../../scripts/windows/info.ps1"
    windows.vm.provision "Setup", type: "shell", reboot: true, path: "../../scripts/windows/setuphyperv.ps1"

    windows.vm.provider :vmware_desktop do |v|
      v.gui = true
      v.memory = "15000"
      v.cpus = 4
      v.vmx['vhv.enable'] = 'TRUE'
      v.vmx['vhv.allow'] = 'TRUE'
      v.vmx["hypervisor.cpuid.0"] = "FALSE"
    end

    windows.vm.provision "file",
      source: "windows-sandbox/Vagrantfile",
      destination: "/Users/vagrant/test/Vagrantfile"

    windows.vm.synced_folder ".", "/Users/vagrant/vagrantdir"
    windows.vm.synced_folder ".", "/vagrant", disabled: true

    windows.trigger.before :provision do |t|
      t.run = {path: "../../scripts/linux/setup-vagrant-gem-dev.sh", args: VAGRANT_VERSION}
    end

    windows.trigger.after :provision do |t|
      t.info = "Time Last Synced"
      t.run = {inline: "date"}
    end

    windows.trigger.after :provision do |t|
      t.info = "Cleaning up workspace"
      t.run = {inline: "bash -c 'rm vagrant-*.gem'"}
    end

    windows.vm.provision "Vagrant Sync", type: :shell,
      run: "never",
      path: "../../scripts/windows/copy-vagrant-gems.ps1",
      args: [VAGRANT_VERSION, VAGRANT_DEV_VERSION]

    windows.vm.provision "SSH", type: "shell", privileged: true, reboot: true,
      path: "../../scripts/windows/setupssh.ps1", run: "never"

    #windows.vm.synced_folder "#{ENV['GOPATH']}/src/github.com/hashicorp/vagrant", "/hashicorp/vagrant/embedded/gems/#{VAGRANT_VERSION}/gems/vagrant-#{VAGRANT_VERSION}"
  end
end
