# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "hyperv" do |w|
    w.vm.box = "windows_2016_hyperv"
    w.vm.synced_folder "../../vagrant-boxes", "/Users/vagrant/vagrant-boxes"

    w.vm.provision "Chocolatey", type: :shell, inline:<<-SHELL
    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    SHELL

    w.vm.provision :shell, inline:<<-SHELL
    choco install packer -y
    SHELL


    w.vm.provision "Packer", type: :shell, env: {"VAGRANT_CLOUD_TOKEN"=>ENV['VAGRANT_CLOUD_TOKEN']}, inline:<<-SHELL
    cd /Users/vagrant/vagrant-boxes/ubuntu
    packer build --only=hyperv-iso ubuntu-18.04-amd64.json
    SHELL
  end
end
