# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "hyperv" do |w|
    #w.vm.box = "windows_2016_hyperv"
    #w.vm.box = "windows_10"
    w.vm.box = "StefanScherer/windows_10"
    w.vm.provision "file",
            source: "../../vagrant-boxes",
            destination: "/Users/vagrant/vagrant-boxes"
            #source: "../../packer-templates/bento",
            #destination: "/Users/vagrant/bento"

    w.vm.provider :vmware_desktop do |v|
      v.gui = true
      v.memory = "10000"
      v.cpus = 4
      v.vmx['vhv.enable'] = 'TRUE'
      v.vmx['vhv.allow'] = 'TRUE'
      v.vmx["hypervisor.cpuid.0"] = "FALSE"
    end

    w.vm.provision "Chocolatey", type: :shell, inline:<<-SHELL
    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    SHELL

    w.vm.provision :shell, reboot: true, inline:<<-SHELL
    choco install packer -y
    DISM /Online /Enable-Feature /All /NoRestart /FeatureName:Microsoft-Hyper-V
    SHELL


    #packer build --only=hyperv-iso ubuntu-16.04-amd64.json
    #cd /Users/vagrant/bento/packer_templates/centos
    #packer build --only=hyperv-iso centos-7.6-x86_64.json
    w.vm.provision "Packer", type: :shell, env: {"VAGRANT_CI_DEV"=>ENV['VAGRANT_CI_DEV'],"VAGRANT_CLOUD_TOKEN"=>ENV['VAGRANT_CLOUD_TOKEN'],"CIRCLE_BUILD_NUM"=>ENV['CIRCLE_BUILD_NUM']}, inline:<<-SHELL
    Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
    cd /Users/vagrant/vagrant-boxes/ubuntu
    packer build --only=hyperv-iso ubuntu-18.04-amd64.json
    SHELL

    # make sure vm isn't running from previous jobs
    w.trigger.after :up do |t|
      t.run = {inline: "vagrant destroy hyperv -f"}
    end
    w.trigger.before :up do |t|
      t.run = {inline: "vagrant destroy hyperv -f"}
    end

  end
end
