# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :vmware_desktop do |v|
    v.cpus = 2
  end

  config.vm.provision "Random", type: "shell", inline:<<-SHELL
  echo '42'
  SHELL

  config.vm.provider :virtualbox do |vb|
    vb.linked_clone = true
  end
end
