# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "cloud_init" do |b|
    b.vm.cloud_init :user_data do |c|
      c.content_type = "text/cloud-config"
      #c.path = "../scripts/data/hello.txt"
      c.inline = <<-CONF
      package_update: true
      CONF
    end

    b.vm.cloud_init content_type: "text/cloud-config", inline: "package_update: true"

    b.vm.box = "hashicorp/bionic64"
    b.vm.provider :virtualbox do |vb|
      #vb.linked_clone = true
    end
  end
  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/bionic64"
    web.vm.cloud_init :user_data, content_type: "text/cloud-config",
      inline: <<-EOF
        package_update: true
        packages:
          - nginx
      EOF
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/bionic64"
    db.vm.cloud_init content_type: "text/cloud-config",
      inline: <<-EOF
        package_update: true
        packages:
          - postgresql
      EOF
  end
end
