# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"


  config.trigger.after :up do |trigger|
    trigger.name = "Greetings"
    trigger.run_remote = {inline: "Write-Host 'Hello there'"}
    trigger.only_on = "windows"
  end

  config.trigger.before :up do |trigger|
    trigger.name = "System Information"
    trigger.info = "Getting information about host..."
    trigger.run = {path: "script.sh"}
  end

  config.trigger.before :up do |trigger|
    trigger.name = "System Information"
    trigger.info = "Getting information about guest..."
    trigger.on_error = :continue
    trigger.run_remote = {path: "script.sh"}
  end

  config.trigger.after :up do |trigger|
    trigger.name = "Update System"
    trigger.info = "Running system update"
    trigger.run_remote = {inline: "echo 'update'"}
    trigger.only_on = /ubuntu/
  end

  config.trigger.before :all do |trigger|
    trigger.name = "ALL"
    trigger.info = "BEFORE ALL ACTIONS"
    trigger.ignore = :up
  end

  config.vm.define "ubuntu" do |m|
    m.vm.box = "bento/ubuntu-16.04"
  end

  config.vm.define "windows" do |m|
    m.vm.box = "windowsbase"
  end
end
