# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.trigger.before :up,
    info: "Tinyproxy",
    run: {inline: "fail"}

  config.trigger.after :destroy,
    info: "Tinyproxy",
    on_error: :continue,
    run: {inline: "brew services stop tinyproxy"}

  config.vm.define "ubuntu" do |m|
    m.vm.box = "bento/ubuntu-16.04"
    m.trigger.before :up, {info: "only 1"}
  end

  config.vm.define "windows" do |m|
    m.vm.box = "windowsbase"
  end
end
