# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provider :virtualbox

  config.vm.provision "D", after: "C", type: "shell", inline:<<-SHELL
  echo 'D'
  SHELL
  config.vm.provision "C", type: "shell", inline:<<-SHELL
  echo 'C'
  SHELL
  config.vm.provision "B", before: "C", type: "shell", inline:<<-SHELL
  echo 'B'
  SHELL
  config.vm.provision "F", after: :all, type: "shell", inline:<<-SHELL
  echo 'F'
  SHELL
  config.vm.provision "A", after: "B", type: "shell", inline:<<-SHELL
  echo 'A'
  SHELL
end
