# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |b|
    b.vm.box = "bento/ubuntu-18.04"
    b.vm.provider :virtualbox
  end

  config.vm.define "hashicorp" do |h|
    h.vm.box = "hashicorp/precise64"
    h.vm.provider :virtualbox
  end

  config.vm.define "windows" do |w|
    w.vm.box = "StefanScherer/windows_10"
    w.vm.synced_folder ".", "/vagrant", disabled: true
    w.vm.network :public_network, bridge: "Default Switch"
  end

  (1..3).each do |i|
    config.vm.define "docker-#{i}"  do |docker|
      docker.vm.provider "docker" do |d|
        d.git_repo = "https://github.com/briancain/nginx-docker-test.git"
        d.cmd = ["tail", "-f", "/dev/null"]
      end
    end
  end

end
