# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANT_VERSION = "2.2.7"

Vagrant.configure("2") do |config|
  config.vm.define "windows-hyperv" do |windows|
    windows.vm.box = "StefanScherer/windows_10" # hyper-v

    # Try regular vagrant first with disk stuff to see
    # usual error message about provider not supported, then
    # continue with synced folders and figure out template issue before
    # trying something else

    #windows.vm.communicator = :winssh
    #windows.ssh.username = "vagrant"
    #windows.ssh.password = "vagrant"
    #windows.winssh.shell = "powershell"

    windows.vm.provision "Info", type: "shell", path: "../scripts/windows/info.ps1"
    windows.vm.provision "Setup", type: "shell", reboot: true, path: "../scripts/windows/setuphyperv.ps1"

    windows.vm.provider :vmware_desktop do |v|
      v.gui = true
      v.memory = "15000"
      v.cpus = 4
      v.vmx['vhv.enable'] = 'TRUE'
      v.vmx['vhv.allow'] = 'TRUE'
      v.vmx["hypervisor.cpuid.0"] = "FALSE"
    end

    windows.vm.provision "file",
      source: "windows-sandbox/Vagrantfile",
      destination: "/Users/vagrant/test/Vagrantfile"

    windows.vm.provision "SSH", type: "shell", privileged: true, reboot: true,
      path: "../scripts/windows/setupssh.ps1", run: "never"

    #windows.vm.synced_folder "#{ENV['GOPATH']}/src/github.com/hashicorp/vagrant", "/hashicorp/vagrant/embedded/gems/#{VAGRANT_VERSION}/gems/vagrant-#{VAGRANT_VERSION}"
    #
    # Try this style of destination path to prevent any weird template issues
    #windows.vm.synced_folder "#{ENV['GOPATH']}/src/github.com/hashicorp/vagrant", "C:\\hashicorp\\vagrant\\embedded\\gems\\#{VAGRANT_VERSION}\\gems\\vagrant-#{VAGRANT_VERSION}"
  end
end
