# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian7" do |d|
    d.vm.box = "bento/debian-7.8"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "debian8" do |d|
    d.vm.box = "bento/debian-8.6"
    #d.vm.box = "debian/jessie64"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "debian9" do |d|
    d.vm.box = "bento/debian-9.4"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "hashicorp" do |d|
    d.vm.box = "hashicorp/precise64"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "ubuntu14" do |d|
    d.vm.box = "bento/ubuntu-14.04"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "ubuntu16" do |d|
    d.vm.box = "bento/ubuntu-16.04"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "ubuntu18" do |d|
    d.vm.box = "bento/ubuntu-18.04"
    d.vm.provider :virtualbox
    d.vm.hostname = "test.test"
    d.vm.synced_folder ".", "/vagrant", disabled: true
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
    d.vm.network "private_network", type: "dhcp"
  end
end
