# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANT_VERSION = "2.2.7"

Vagrant.configure("2") do |config|
  config.ssh.username = "root"

  (1..3).each do |i|
    config.vm.define "docker-#{i}"  do |docker|
      docker.vm.network :forwarded_port, guest: 80, host: 8080
      docker.vm.provider "docker" do |d|
        d.build_dir = "."
        d.has_ssh = true
        d.remains_running = true
      end
    end
  end
end
