# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.disk :disk, size: "64GB", primary: true

  config.vm.disk :disk, size: "10GB", name: "provider_disk"

  (1..3).each do |i|
    config.vm.disk :disk, size: "5GB", name: "smaller-disk-#{i}"
  end

  config.vm.define "ubuntu" do |b|
    b.vm.box = "bento/ubuntu-18.04"
    b.vm.synced_folder ".", "/vagrant", disabled: true
    b.vm.network :public_network, bridge: "Default Switch"
  end

  config.vm.define "hashicorp", primary: true do |h|
    h.vm.box = "hashicorp/bionic64"
    h.vm.synced_folder ".", "/vagrant", disabled: true
    h.vm.network :public_network, bridge: "Default Switch"
  end
end
