# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "disk" do |b|
    b.vm.box = "hashicorp/bionic64"

    #b.vm.disk :disk, size: "150GB",
    b.vm.disk :disk, size: "64GB",
      virtualbox__diskoption: "1234", libvirt__otheroption: true, primary: true

    # Or the hash syntax...
    disk_options = {diskoption: "1234", otheroption: true}

    b.vm.disk :disk, size: "10GB", name: "provider_disk",
      virtualbox: disk_options, libvirt: disk_options

    (1..3).each do |i|
      b.vm.disk :disk, size: "5GB", name: "smaller-disk-#{i}",
        virtualbox: disk_options
    end

    b.vm.provider :virtualbox do |vb|
      #vb.linked_clone = true
    end
  end
end
