# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04" # 16.04 LTS

  config.vm.provision "Docker", type: "shell", path: "scripts/install-docker.sh", privileged: false
  config.vm.provision "Nomad & Consul", type: "shell", path: "scripts/install-nomad-consul.sh", privileged: false

  # Expose the nomad api and ui to the host
  config.vm.network "forwarded_port", guest: 4646, host: 4646, auto_correct: true

  config.vm.define "leader" do |l|
    l.vm.hostname = "leader.nomad"
    # Server port
    l.vm.network "forwarded_port", guest: 4647, host: 4647
    l.vm.network "public_network", ip: "192.168.50.100"
    l.vm.provision "Leader", type: "shell", path: "scripts/setup-leader.sh", privileged: false
  end

  (1..3).each do |i|
    config.vm.define "follower-#{i}" do |f|
      f.vm.hostname = "follower-#{i}.nomad"
      f.vm.provision "Follower", type: "shell", path: "scripts/setup-follower.sh", privileged: false
    end
  end

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "1024"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "1024"
    end
  end
end
